import {
  AI_MODELS,
  STAGE5_ELEVENLABS_SCRIBE_MODEL,
  STAGE5_REVIEW_TRANSLATION_MODEL,
  STAGE5_TRANSCRIPTION_MODEL_PRICING,
  STAGE5_TRANSLATION_MODEL_PRICING,
  STAGE5_TTS_MODEL_ELEVEN_MULTILINGUAL,
  STAGE5_TTS_MODEL_PRICING,
  STAGE5_TTS_MODEL_STANDARD,
  STAGE5_WHISPER_MODEL,
} from './model-catalog';

export const OPENAI_WEB_SEARCH_USD_PER_CALL = 10 / 1_000;
export const ANTHROPIC_WEB_SEARCH_USD_PER_CALL = 10 / 1_000;

export const VENDOR_TOKEN_MODEL_PRICING = {
  [AI_MODELS.GPT]: STAGE5_TRANSLATION_MODEL_PRICING[AI_MODELS.GPT],
  [STAGE5_REVIEW_TRANSLATION_MODEL]:
    STAGE5_TRANSLATION_MODEL_PRICING[STAGE5_REVIEW_TRANSLATION_MODEL],
  [AI_MODELS.CLAUDE_SONNET]: {
    in: 3 / 1_000_000,
    out: 15 / 1_000_000,
  },
  [AI_MODELS.CLAUDE_OPUS]: STAGE5_TRANSLATION_MODEL_PRICING[AI_MODELS.CLAUDE_OPUS],
} as const;

export type VendorTokenModelId = keyof typeof VENDOR_TOKEN_MODEL_PRICING;

export const ELEVENLABS_PLAN_TIERS = [
  'creator',
  'pro',
  'scaleBusiness',
] as const;

export type ElevenLabsPlanTier = (typeof ELEVENLABS_PLAN_TIERS)[number];

export const VENDOR_TRANSCRIPTION_MODEL_PRICING = {
  [STAGE5_WHISPER_MODEL]: STAGE5_TRANSCRIPTION_MODEL_PRICING[STAGE5_WHISPER_MODEL],
  [STAGE5_ELEVENLABS_SCRIBE_MODEL]: {
    creator: 0.48 / 3600,
    pro: 0.4 / 3600,
    scaleBusiness: 0.22 / 3600,
  },
} as const;

export const VENDOR_TTS_MODEL_PRICING = {
  [STAGE5_TTS_MODEL_STANDARD]: STAGE5_TTS_MODEL_PRICING[STAGE5_TTS_MODEL_STANDARD],
  [STAGE5_TTS_MODEL_ELEVEN_MULTILINGUAL]: {
    creator: 300 / 1_000_000,
    pro: 180 / 1_000_000,
    scaleBusiness: 120 / 1_000_000,
  },
} as const;
